# Define the menu links for this module

entity.my_config.list:
  title: 'Content Entity Example: Contacts Listing'
  route_name: entity.my_config.list
  description: 'List Contacts'
  weight: 10
# my_config.admin.structure.settings:
#   title: Contact Settings
#   description: 'Configure Contact entity'
#   route_name:  content_entity_example.contact_settings
#   parent: system.admin_structure
