<?php

/**
 * @file
 * Common functions for all projects.
 */

use Drupal\Core\DrupalKernel;
use Symfony\Component\HttpFoundation\Request;

//module_load_include('inc', 'oo_common', 'convert');
//module_load_include('inc', 'oo_common', 'utility');
//module_load_include('inc', 'oo_common', 'date');
//module_load_include('inc', 'oo_common', 'file');
//module_load_include('inc', 'oo_common', 'excel');
//module_load_include('inc', 'oo_common', 'entity');

/**
 * Implements hook_theme().
 *
 * Auto register theme from get_project_themes
 * (sites/[directory alias]/project.settings.php)
 */
function oo_common_theme($existing, $type, $theme, $path) {
  $commonSettingFilename = get_common_settings_filename();
  if (!empty($commonSettingFilename)) {
    require_once $commonSettingFilename;
    $themes = get_project_themes();
    $data = array();
    foreach ($themes as $key => $item) {
      $data[$key] = array(
        'variables' => isset($item['variables']) ? $item['variables'] : array('data' => NULL),
        'template' => isset($item['template']) ? $item['template'] : str_replace('-', '_', $item['name']),
      );
    }
    return $data;
  }
  return array();
}

/**
 * Implements hook_mail().
 */
function oo_common_mail($key, &$message, $params) {
  switch ($key) {
    case 'oo_mail':
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['body'];
      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed';
      break;
  }
}

/**
 * Implements hook_mail_alter().
 */
function oo_common_mail_alter(&$message) {
  $commonSettingFilename = get_common_settings_filename();
  if (!empty($commonSettingFilename)) {
    require_once $commonSettingFilename;
    $keys = get_disable_send_mail_keys();
    if (!empty($keys)) {
      if (in_array($message['key'], $keys)) {
        $message['send'] = FALSE;
      }
    }
  }
}

/**
 * Get common settings filename.
 *
 * @return mixed
 *   String if find the file path, NULL if not found.
 */
function get_common_settings_filename() {
  $autoloader = require_once DRUPAL_ROOT . '/autoload.php';
  $request = Request::createFromGlobals();
  $configDir = DrupalKernel::findSitePath($request);
  $commonSettingFilename = DRUPAL_ROOT . '/' . $configDir . '/project.settings.php';
  if (file_exists($commonSettingFilename)) {
    return $commonSettingFilename;
  }
  return NULL;
}

function pr($data, $exit = 0){
  print '<pre>';
  print_r($data);
  print '</pre>';
  if($exit == 1){
    die;
  }
}

function create_url_by_node_id($nid){
  $url = Drupal\Core\Url::fromRoute('entity.node.canonical', ['node' => $nid], ['absolute' => TRUE]);
  return $url->toString();
}
