<?php

/**
 * @file
 * my_base module file.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Link;
use Drupal\Core\Url;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\node\Entity\Node;
use Drupal\Core\Database\Database;
use Drupal\Core\Render\Markup;

define('AP_API_ERR_MSG_400', 'The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).');
define('AP_API_ERR_MSG_401', 'The request has not been applied because it lacks valid authentication credentials for the target resource.');
define('AP_API_ERR_MSG_403', 'The server understood the request but refuses to authorize it.');
define('AP_API_ERR_MSG_404', 'The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.');
define('AP_API_ERR_MSG_500', 'The server encountered an unexpected condition that prevented it from fulfilling the request.');
define('CAMPAIGN_COOKIE_NAME', 'nestle_gerber_2017');

/**
 * Implements hook_theme().
 */
function my_base_theme($existing, $type, $theme, $path) {

  $themes = [];
  $themes['home_page'] = [
    'render element' => 'build',
    'template' => 'layout/home-page',
  ];

  $themes['about_us_page'] = [
    'render element' => 'build',
    'template' => 'layout/about-us-page',
  ];

  $blocks = [
    'header_block',
    'footer_block',
    'topcommon_block',
  ];
  if (!empty($blocks)) {
    foreach ($blocks as $item) {
      $themes[$item] = [
        //'variables' => ['params' => NULL],
        'render element' => 'build',
        'template' => 'block/' . $item,
      ];
    }
  }

  return $themes;
}

function my_base_node_view(array &$build, EntityInterface $node, EntityViewDisplayInterface $display, $view_mode) {

  /*switch ($node->getEntityTypeId()) {
    case 'node':
      $build = my_base_handle_entity_node($build, $node, $view_mode);
      break;

    default:
      # code...
      break;
  }*/
}


function my_base_preprocess_views_view(&$variables) {


}

/**
 * Implements hook_mail().
 */
function my_base_mail($key, &$message, $params) {
}



/**
 * Implements hook_entity_update().
 */
function my_base_entity_update(EntityInterface $entity) {


}

/**
 * Implements hook_entity_delete().
 */
function my_base_entity_delete(EntityInterface $entity) {

}

/**
 * Implements hook_page_attachments_alter().
 */
function my_base_page_attachments_alter(array &$attachments) {

  foreach ($attachments['#attached']['html_head'] as $key => $attachment) {
    if (isset($attachment[1]) && $attachment[1] == 'system_meta_generator') {
      unset($attachments['#attached']['html_head'][$key]);
    }
  }
}

function my_base_handle_entity_node(array &$build, $entity, $view_mode){

  if($view_mode ==  'full'){
    $node_type = $entity->bundle();
    switch ($node_type) {
      case 'about_us_page':
        $object = new \Drupal\my_base\Controller\AboutUsController();
        $var = $object->get_data($entity);
        $build['#data'] = $var['#data'];
        $build['#theme'] = $var['#theme'];
        break;

      default:
        # code...
        break;
    }
  }

  return $build;

}
